# Generated by Django 5.2.4 on 2026-04-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPathApp', '0003_remove_subject_user_material_currentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to='static/'),
        ),
    ]
