# Generated by Django 5.2.4 on 2026-05-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduPathApp', '0004_alter_material_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to='static/'),
        ),
    ]
